packages/frontend/src/hooks/usePositions.ts

LP positions are not loading because BigNumber.js not compatible with BigIntish. So directly used it as string
- Create LP position in uniswap
- Check the LP position page and it should load properly

Fix LP loading issue

---

packages/frontend/src/components/Charts/LongChart.tsx

- Colors were off on sqth and eth
Locally

fix: pnl legend

---

packages/frontend/package.json
packages/frontend/src/components/Button/WalletButton.tsx
packages/frontend/src/hooks/useENS.ts
yarn.lock

Add ens name and avatar support
We done the same in gamma frontend https://github.com/opynfinance/Gamma-Frontend/pulls?q=is%3Apr+ens+is%3Aclosed
Just login with the account that has ens name

feat: add ens name and avatar support

---

packages/frontend/pages/index.tsx
packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Charts/VaultChart.tsx
packages/frontend/src/components/Nav.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/hooks/contracts/useController.ts

- Link logo to landing page 
- Add Unipool swap links to the trades on univ3 message 
- Update funding tooltips and descriptions 
- Add Sherlock to audits
Locally

Fe: update links and copy

---

packages/frontend/README.md
packages/frontend/src/context/wallet.tsx
yarn.lock

Switch provider from infura to alchemy
We are close to hitting our usage limits on infura. So switching to alchemy for higher limits and speed
made NEXT_PUBLIC_USE_ALCHEMY=true locally in my .env file and loaded the app and looked at the network calls
everything is working fine without any issues

chore(network): switch to alchemy

---

packages/hardhat/contracts/core/Controller.sol

onlly -> only

---

packages/frontend/src/components/Button/WalletButton.tsx
packages/frontend/src/context/wallet.tsx

- Let users disconnect their wallet from within the app by clicking on their connected address
Locally

Fe: Disconnect wallet

---

packages/frontend/pages/positions.tsx
packages/frontend/src/components/Trade/Short/index.tsx

- Add a check to prevent dust on short/close by making sure the position calculations match the shortAmount on chain
Locally

fix: add a check to prevent dust on short/close

---

packages/frontend/src/hooks/useInterval.ts

reverting a hook that maybe not working as expected 
reverting a hook that maybe not working as expected 
unresponsive squeeth.com should be addressed
locally ran  it fine

revert useInterval

---

packages/frontend/pages/positions.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/hooks/usePositions.ts

fix: short position closing issue

---

packages/frontend/src/constants/enums.ts

Address wasn't updated earlier for the unipool
Locally

update ropsten address for uniswap pool

---

packages/frontend/pages/positions.tsx

added dep to make positions on position page show up

fix: positions wont show up on position page

---

packages/hardhat/README.md
packages/hardhat/contracts/strategy/CrabStrategy.sol
packages/hardhat/contracts/strategy/base/StrategyBase.sol
packages/hardhat/contracts/strategy/base/StrategyFlashSwap.sol

Update license for crab strategy contracts

Chrore: Update license for launch

---

packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx

Show error and disable button if max cap hit
Locally

feat: add max cap warning

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfo.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/constants/enums.ts

- Gives users insufficient balance warnings on deposit and withdraw 
- Copy updates to max profit threshold clearer
Locally

fix: strategy error handling and copy updates

---

packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/hooks/usePositions.ts

1. disable action button if vault is not loaded and user doesn't have input
2. return 0 if vault doesn't have valid value
3. need to move error msg out of useEffect, otherwise they will disappear after each re-rendering
Fixes #100  (issue) 
locally

fix: fe vault loading issue

---

packages/frontend/src/hooks/usePositions.ts

1. removed unnecessary items in dep array
Fixes #94 
Locally

fix: position flickering & switching issue

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/context/crabStrategy.tsx

Shows strategy price impact for deposits and withdraws (video from ropsten) 
https://user-images.githubusercontent.com/13340486/150876067-69d9b1e1-108c-4741-8108-c6b2810d7403.mov
Locally

feat: show strategy price impact

---

packages/frontend/src/lib/pnl.ts

This PR fixes the issue of dollar pnl showing nan for a user on position page and card
#95 
You can test this PR by ensuring unrealized pnl on position card and position page is not nan

Dollar PnL was NaN for user on positions page and positions card

---

packages/frontend/pages/positions.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Strategies/Crab/CrabPosition.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/context/crabStrategy.tsx
packages/frontend/src/hooks/contracts/useController.ts
packages/frontend/src/queries/squeeth/crabAuctionQuery.ts

- Fix PnL to show amountOut instead of amountMinOut
- Fix ethToBorrow calculation to consider both increment and decrement cases
- Compare the PnL with squeeth.com

Fix PnL and ethToBorrow calculation

---

packages/frontend/src/components/Trade/Short/index.tsx

For some reason the short check wasn't using the correct value if the contract amount was diff from the calculated amount 
Locally

fix: final short check

---

packages/frontend/src/components/Strategies/Crab/CapDetails.tsx

if deposits > cap, show cap on bar 
Locally

fix: update max cap if deposits > cap from hedge

---

packages/frontend/package.json
packages/frontend/src/context/wallet.tsx

Add coinbase desktop wallet support
Add gnosis wallet support
Adding wallet support for coinbase and gnosis ( some users are facing issues)
40
Tested locally

add coinbase and gnosis wallet support

---

packages/frontend/package.json
packages/frontend/src/context/wallet.tsx

Reverts opynfinance/squeeth-monorepo#127

Revert "add coinbase and gnosis wallet support"

---

packages/frontend/src/context/wallet.tsx

add coinbase and gnosis wallet support 
add coinbase and gnosis wallet support 
Tested locally. Did buy/sell squeeth on ropsten

new wallets without updating onboard version

---

packages/frontend/src/markdown/terms-of-service.md

This PR updates the terms of service. see updates [here](https://docs.google.com/document/d/1-dP-MI4lPsowCJsYCSwm-pf3n-ZOKrgx6h8ATTsAzN0/edit)

refactor: updates to terms of service

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx

Used a wrong if check so changed it
Fixes #139 
- [] Added video recordings if it is a UI change

Disable warning if auction is not running

---

packages/frontend/src/context/wallet.tsx

removed the s after Terms of Service and Capitalized Privacy Policy

---

packages/frontend/pages/lp.tsx
packages/frontend/src/components/Charts/LPBuyChart.tsx
packages/frontend/src/components/Charts/LPMintChart.tsx
packages/frontend/src/components/Lp/LPPosition.tsx
packages/frontend/src/components/Lp/ObtainSqueeth.tsx
packages/frontend/src/components/Lp/SqueethInfo.tsx
packages/frontend/src/hooks/usePositions.ts
packages/frontend/src/utils/pricer.ts

Add buy vs mint LP comparison

---

packages/frontend/pages/lp.tsx
packages/frontend/pages/positions.tsx
packages/frontend/src/components/PositionCard.tsx
packages/frontend/src/hooks/usePositions.ts
packages/frontend/src/lib/pnl.ts

fix: removes ethCollateralpnl temporarily

---

packages/frontend/pages/index.tsx
packages/frontend/src/constants/enums.ts

- Show normFactor in advanced details on the trade page since many users have been requesting to see it on the frontend vs. having to go to the contract or Dune 
#147 
Locally

feat: add norm factor 

---

packages/frontend/pages/_app.tsx
packages/frontend/src/context/restrict-user.tsx

This PR Removes ropsten blocking
#141 

Stop user from being restricted on ropsten

---

packages/frontend/src/hooks/usePositions.ts

1. update dep array 
Fixes #151  (issue)
Locally

fix: position switching issue

---

packages/frontend/custom.d.ts
packages/frontend/package.json
packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/abis/erc721.json
packages/frontend/src/hooks/contracts/useController.ts
packages/frontend/src/hooks/contracts/useERC721.ts
packages/frontend/src/hooks/contracts/useNFTManager.ts
packages/frontend/src/hooks/contracts/useSqueethPool.ts
packages/frontend/src/hooks/useVaultData.ts
yarn.lock

Add UI flow to deposit LP NFT as collateral
Fixes #157 
- New card to manage LP NFT will appear in vault manager
- Type your token approve and deposit

Add ability to use LP NFT as collateral in FE

---

packages/frontend/pages/_app.tsx
packages/frontend/pages/positions.tsx
packages/frontend/src/components/Charts/CrabStrategyChart.tsx
packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Charts/ShortChart.tsx
packages/frontend/src/components/Charts/VaultChart.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfo.tsx
packages/frontend/src/context/positions.tsx
packages/frontend/src/context/wallet.tsx
packages/frontend/src/context/world.tsx
packages/frontend/src/hooks/contracts/useTokenBalance.ts
packages/frontend/src/hooks/useETHPrice.ts
packages/frontend/src/hooks/useETHPriceCharts.tsx
packages/frontend/src/hooks/useTransactionHistory.ts
packages/frontend/src/hooks/useUsdAmount.ts
packages/frontend/src/lib/pnl.ts

-  update API calls to use react-query
> What are the places that need testing?
- getETHPriceCoingecko - fetches current ethPrice from coingecko
- useETHPriceCharts
> What would be the improvement?
- The getETHPriceCoingecko fetch is not affected by re-renders, it’ll only fetch when it’s supposed to which is at the specified interval. You can test this by checking the network tab on the initial render to ensure that the ``https://api.coingecko.com/api/v3/simple/price?ids=${coin}&vs_currencies=usd`` network call occurs only once initially and updates only at the specified interval.
- The other cached API calls that do not run on intervals have a more consistent caching.
> The APIs that are now using react-query
- ``https://api.coingecko.com/api/v3/simple/price?ids=${coin}&vs_currencies=usd` …

Use react-query for API calls 

---

packages/frontend/src/queries/uniswap/swapsQuery.ts

Swaps query is failing because pool address is not used

Add pool address to the query

---

packages/frontend/src/components/Charts/FundingChart.tsx
packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Charts/ShortChart.tsx
packages/frontend/src/components/CustomSwitch.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/hooks/useNormHistory.ts
packages/frontend/src/queries/uniswap/normHistoryQuery.ts
packages/frontend/src/types/index.ts
packages/frontend/src/utils/index.tsx

Add historical funding graph to trade page
Fixes #97  (issue)
Tested locally

Add funding graph

---

packages/frontend/pages/vault/[vid].tsx

Fix LP NFT not loading

---

packages/frontend/src/context/wallet.tsx

add pokt support
Adding pokt network as RPC service provider
note: merging this wont make pokt default rpc provider. we should also change the flags in .env after
Tested the normal operations ( buy, sell, mint + sell etc ) on my local
Saw in network tab that calls are going to pokt instead of alchemy.
also seen in the pokt account dashboard that the calls are being served without errors

add pokt support

---

packages/frontend/src/components/Charts/FundingChart.tsx
packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/LegendBox.tsx
packages/frontend/src/context/world.tsx
packages/frontend/src/hooks/useETHPriceCharts.tsx
packages/frontend/src/hooks/useNormHistoryFromTime.ts
packages/frontend/src/queries/uniswap/normHistoryQuery.ts
packages/frontend/src/utils/pricer.ts

- Add hook to get NormFactor History from timestamps array
- Add hook to get squeeth PNL data with live VOL
- Change funding graph label from `Annual` to `Annualized`
Fixes #32 
Tested locally

Update backtest data

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/FlashControllerHelper.sol
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

This PR add the flash mint functionality, where the helper contract flashswap the amount of ETH collateral needed to mint from uniswap pool, and repay it with the minted wPowerPerp amount.

feat: flash mint

---

packages/frontend/pages/api/twelvedata.ts
packages/frontend/src/hooks/useETHPrice.ts

feat: Use twelvedata api through proxy to fetch eth price

---

packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/LegendBox.tsx

Add tooltip to simulated PNL legendBox and replace where it says "Deribit" with "Simulated" on PNL chart
Fixes #219 
Tested locally

Clarify historical PnL simulation

---

packages/hardhat/test/integration-tests/liquidation.ts
packages/hardhat/test/integration-tests/short_helper_integration.ts
packages/hardhat/test/integration-tests/strategy/crab-flashswap-liquidation.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-dust.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-full.ts
packages/hardhat/test/integration-tests/strategy/crab-shutdown.ts
packages/hardhat/test/unit-tests/controller-lptoken-collateral.ts
packages/hardhat/test/unit-tests/controller.ts

Fix old tests issues due to using gasPrice(0)
- Added txCost from the transaction
- Include txCost in the expression to check liquidator balance

Fix old tests issues due to using gasPrice(0)

---

.circleci/config.yml
packages/hardhat/ci/e2e.sh

Add infura key in circle ci vars and include mainnet fork in jobs
Add infura key in circle ci vars and include mainnet fork in jobs

Add infura key in circle ci vars and include mainnet fork in jobs

---

packages/frontend/pages/positions.tsx
packages/frontend/src/context/crabStrategy.tsx
packages/frontend/src/context/world.tsx
packages/frontend/src/hooks/contracts/useTokenBalance.ts
packages/frontend/src/hooks/useCrabPosition.ts

Fix loading state of crab positions.
https://github.com/opynfinance/squeeth-monorepo/issues/209

Fix loading in crab positions

---

packages/hardhat/hardhat.config.ts

Update hardhat config to fix coverage test

fix: update hardhat config to fix coverage test

---

packages/hardhat/hardhat.config.ts
packages/hardhat/test/integration-tests/liquidation.ts
packages/hardhat/test/integration-tests/short_helper_integration.ts
packages/hardhat/test/integration-tests/strategy/crab-flashswap-liquidation.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-dust.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-full.ts
packages/hardhat/test/integration-tests/strategy/crab-shutdown.ts
packages/hardhat/test/unit-tests/controller-lptoken-collateral.ts
packages/hardhat/test/unit-tests/controller.ts

Fix integration test
Fix expression in integration test

Fix integration test

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/liquidation.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/short_helper_integration.ts
packages/hardhat/test/integration-tests/strategy/crab-flashswap-liquidation.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-dust.ts
packages/hardhat/test/integration-tests/strategy/crab-liquidation-full.ts
packages/hardhat/test/integration-tests/strategy/crab-shutdown.ts
packages/hardhat/test/unit-tests/controller-lptoken-collateral.ts
packages/hardhat/test/unit-tests/controller.ts

fix: rebase issues

---

packages/frontend/pages/api/charts/longchart.ts

Fix long squeeth PNL graph
Fix long squeeth PNL graph to show correct data
https://opyn.slack.com/archives/C02QMRTJX5J/p1648075862958339
Tested locally

Fix long squeeth PNL graph

---

packages/frontend/src/hooks/useCrabPosition.ts

Crab PNL is not loading properly
Update memo and useEffect dependency
Fixes #256 
https://github.com/opynfinance/squeeth-monorepo/issues/256

Update depdancy array

---

packages/frontend/src/hooks/useVaultData.ts
packages/frontend/src/state/controller/hooks.ts
packages/frontend/src/state/nftmanager/hooks.ts

https://opyn.slack.com/archives/C02QMRTJX5J/p1648194664602209
Fix vault collateral percent not showing properly

Fix vault collateral

---

packages/frontend/src/components/Trade/Short/index.tsx

changed default CR on short to 200%
Fixes #28 (issue)

fix: changed default CR on short to 200%

---

packages/frontend/src/state/positions/hooks.ts

Long squeeth not loading.
Updated dependency to calculate squeeth properly
https://opyn.slack.com/archives/C02QMRTJX5J/p1648599317947579

Fix long squeeth not loading

---

packages/frontend/src/state/crab/hooks.ts

ethToBorrow is set as 0 because of improper dependency array

Fix: ethToBorrow is set as 0

---

packages/frontend/src/hooks/useCrabPosition.ts
packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/squeethPool/hooks.ts

Crab shows bloated values
Checked production values

Fix: crab UI show wrong PnL 

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol

This PR fix the issues of trapped burnt NFT in ControllerHelper.sol
Fixes #296 

fix: return burnt NFT to user

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

When decreasing liquidity from LP position, redeposit into vault to not revert with undercollateralized error.
Fixes #310 

fix: revert tx for partially closing LP

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

fix: wrapping ETH for flashloan payment

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/hardhat.config.ts

Check vault ownership in parent function

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol

feat: general swap

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/UniswapControllerHelper.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/package.json
packages/hardhat/test/integration-tests/periphery/controller-helper.ts
packages/hardhat/test/setup.ts

Reverts opynfinance/squeeth-monorepo#327

Revert "Improve ControllerHelper tests"

---

packages/hardhat/test/integration-tests/periphery/controller-helper.ts

- adds missing tests for sell long + go short flows
- adds missing tests for close short + go long flows

Close long and short / Close short and long ControllerHelper tests

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

- Add checkClosedLp() 
- Rename sellAll() to reduceLiquidityAndSell() and allow increasing liquidity within same ranges
Fixes #302 & #345 

feat: add increasing liquidity within same ranges and rename sellAll()

---

packages/frontend/pages/index.tsx
packages/frontend/pages/lp.tsx
packages/frontend/pages/positions.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/components/Button/WalletButton.tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/state/wallet/atoms.ts
packages/frontend/src/state/wallet/hooks.ts

- Add unsupported network button on header
- Disable all trades on unsupported chains.
Fixes #162 

Add unsupported network

---

packages/frontend/src/pages/positions/Positions.tsx

Hide crab position if not deposited on positions page
Hide crab position if not deposited on positions page
Fixes #362 

Hide crab position if not deposited on positions page

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/hooks/useAppCallback.tsx
packages/frontend/src/hooks/useAppEffect.tsx
packages/frontend/src/hooks/useAppMemo.tsx
packages/frontend/src/state/ethPriceCharts/atoms.ts
packages/frontend/src/utils/pricer.ts
packages/frontend/src/utils/stringifyDeps.ts

Fix crab withdraw is not working
https://opyn.slack.com/archives/C02QMRTJX5J/p1650953734289379
It was related to the infinite rerendering of CrabStrategyChart. Several hooks in the CrabStrategyChart return real-time arrays that don't contain the id property and it causes app hooks to recalculate every time.  This PR extended app hooks to support tracking dependency using array length. 

Update app hooks and dependency of atoms and pricer

---

packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/hooks/useVaultHistory.ts
packages/frontend/src/state/positions/hooks.ts

Fix flickering on vault page
- Add a hook to load LPed debt on vault page
- Update vault history and swap hooks only when the subgraph query returns data
Fixes #372 

Fix flickering on vault page

---

packages/frontend/src/state/positions/providers.tsx

Squeeth amount may not be equal to users long amount, need to check if they actually have that balance in their wallet, temporary fix for some of the edge cases

fix: add wallet balance check for squeeth amount

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

Redeposit NFT back into vault
Fixes #381 

Fix: redeposit NFT into vault when increasing liquidity

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts

- add ability for a user to atomically withdraw a uni NFT from a vault to collect fees and re-deposit
Fixes #382 

Add ability to collect fees and deposit nft in vault actions

---

packages/frontend/src/components/PositionCard.tsx
packages/frontend/src/pages/positions/LongSqueeth.tsx

Removed some checks that are not needed

Remove unwanted check to show loading

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/contracts/periphery/lib/LiquidityAmounts.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

Fix excess amounts when LPing

---

packages/frontend/src/components/Input/PrimaryInput.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/hooks/contracts/useTokenBalance.ts
packages/frontend/src/state/positions/hooks.ts

- Adds activity update for when sqthBal is loading or when there is an error loading the sqth bal.
- Allow user to refetch incase sqth bal fails to load. 
#220 

Long/Close didn't load a user's oSQTH balance

---

packages/frontend/src/hooks/contracts/useTokenBalance.ts
packages/frontend/src/state/positions/providers.tsx

Fix position card not updating when opening long and short positions
Fixes #409  (issue)

Fix position card not updating when opening lp

---

packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol

Fix: vaultId = 0 returned from mintAndLp()

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

Fix burn bug

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol

This PR allow to use ControllerHelper WPowerPerp balance to increase LP liquidity.
Fixes #412 

fix: use contract balance to increase liquidity

---

packages/frontend/src/pages/positions/LongSqueeth.tsx
packages/frontend/src/pages/positions/ShortSqueeth.tsx
packages/frontend/src/state/positions/providers.tsx

Fixed realized PnL not loading in short card in trade and positions page
https://github.com/opynfinance/squeeth-monorepo/issues/375

Fix realized pnl not loading

---

packages/frontend/src/state/wallet/hooks.ts

Add Coinbase Wallet to the preferred list. We left the order and other preferred wallets the same. Please let me know if any other updates are needed.
Manually in the UI. Screenshot below

Make CB Wallet preferred

---

packages/frontend/src/components/Strategies/Crab/StrategyInfo.tsx

Hide Crab PnL charts
https://opyn.slack.com/archives/C02QMRTJX5J/p1652058045736449?thread_ts=1651940689.543599&cid=C02QMRTJX5J

Hide pnl charts

---

packages/frontend/pages/vault/[vid].tsx

Fix issues on vault page
- Hide collateral Ratio and action buttons when selecting None for lp Token on vault page
- Fix max amount to remove collateral on vault page
Fixes #419 

Fix issues on vault page

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx

Add clearer warnings if squeeth is trading at a higher / lower vol than average

Update funding high error

---

packages/frontend/src/components/Trade/TradeInfoItem.tsx
packages/frontend/src/components/Trade/UniswapData.tsx

Current this is what we are doing
less than 1% -> green
Less than 3% -> white
More than 3% -> Red
New changes will be
Less than 1% -> green
Less than 2% -> yellow
More than 2% -> Red
[hello](https://user-images.githubusercontent.com/24666922/167974830-fbfc1328-5221-4d0d-ac2b-0abcf82ac3d6.mov)

Update colours for price imapct

---

packages/frontend/cypress/integration/specs/02-trade-short.spec.js
packages/frontend/src/components/CollatRange.tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx
packages/frontend/src/components/Trade/Short/index.tsx

reverts recent changes to collateral ratio 

---

packages/hardhat/test/e2e/periphery/controller-helper.ts

fix CI tests issue

---

packages/frontend/src/hooks/useCrabPosition/mocks.ts
packages/frontend/src/hooks/useCrabPosition/useCrabPosition.test.tsx

Fix failing FE test

---

packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol

Fix: increaseLpLiquidity()

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

Fix: general swap fail when amountIn is greater than balance

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

Refactor: transfer back WPowerPerp in FLASH_W_BURN

---

.github/pull_request_template.md

Adds user facing checklist to PR template to make sure we are thinking of the user in everything we are shipping
n/a
n/a
n/a

docs: add user facing checklist to PR template

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

- Fixes #481
- Fixes #475 
- Fixes #473 
- Fixes #443 

Fix ControllerHelper

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

- Remove redundant weth deposit
- remove unnecessary return statement
fixes #452

Feat: Remove redundant code

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

Fix #491 & #492

---

packages/frontend/package.json
packages/frontend/pages/_app.tsx
packages/frontend/pages/_middleware.ts
packages/frontend/src/components/RestrictionInfo.tsx
packages/frontend/src/constants/index.ts
packages/frontend/src/context/restrict-user.tsx
packages/frontend/src/markdown/privacy-policy.md
yarn.lock

- removes cookie
- updates code to suit changes
- updates privacy policy

removes cookie

---

packages/hardhat/contracts/libs/VaultLib.sol
packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol

- Add require statement to check ControllerHelper hold no LP NFT at the end of `rebalanceLpInVault()`
- Clean console.log

Fix: add require for checking LP NFT balance

---

packages/hardhat/ci/e2e.sh
packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts

- add fixed block number for mainnet fork in e2e testing
- Update comments around the general swap action to make it clear it will cause loss of funds if used with any token other than weth and wPowerPerp

update comments for generalSwap and update e2e to use fixed block for mainnet fork

---

packages/frontend/src/state/squeethPool/hooks.ts
yarn.lock

fix: fix fe rerender issue

---

packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/crab/utils.ts

https://github.com/opynfinance/squeeth-monorepo/issues/519
Fix crab nav value
Fixes # (issue) https://github.com/opynfinance/squeeth-monorepo/issues/519

Fix crab nav value

---

packages/hardhat/test/e2e/crab-Migration.ts

Fixed e2e tests for batch migrate. 
They pass while running them on my laptop

e2e tests fixed

---

packages/hardhat/README.md
packages/hardhat/ci/e2e.sh
packages/hardhat/contracts/strategy/CrabStrategyV2.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/package.json
packages/hardhat/test/e2e/crab-Migration.ts
packages/hardhat/test/integration-tests/crabv2/crab-hedging-otc.ts

- Stop running E2E tests in unit test
- Add command for running E2E test
- Add in readme

Fix E2E tests

---

packages/hardhat/contracts/strategy/CrabStrategyV2.sol
packages/hardhat/test/integration-tests/crabv2/crab-hedging-otc.ts

Missed updating priceAtLastHedge in hedge function. Update it now; with test

setPriceAtLastHedge in hedge function

---

.circleci/config.yml
packages/hardhat/README.md
packages/hardhat/contracts/strategy/CrabMigration.sol
packages/hardhat/contracts/strategy/base/StrategyMath.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/test/e2e/crab-Migration.ts
packages/hardhat/test/unit-tests/strategy/crab-migration.ts
packages/hardhat/test/utils.ts

Add individual migration

---

packages/hardhat/contracts/strategy/CrabMigration.sol

Removed extra crab approve in batch migrate

Fix: Removed extra crab approve in batch migrate

---

packages/hardhat/contracts/strategy/CrabStrategyV2.sol

Sets maxOTCPriceTolerance to a constant and changes formatting to indicate a constant variable

[Audit Fix] - [I-17] - State variable could be declared constant

---

packages/hardhat/contracts/strategy/CrabStrategyV2.sol
packages/hardhat/test/unit-tests/strategy/crab-strategy-v2.ts

Added a check to ensure that hedgePriceThreshold is <= 1e18

[Audit Fix] - [I-16] - hedgePriceThreshold does not have a sanity check

---

packages/hardhat/contracts/strategy/CrabHelper.sol
packages/hardhat/contracts/strategy/CrabStrategyV2.sol

Removed 3 unused state variables

[Audit Fix] - [I-9] - Unused state variable

---

packages/hardhat/contracts/strategy/CrabStrategyV2.sol
packages/hardhat/test/integration-tests/crabv2/crab-hedging-otc.ts

Added tests for EIP 712 attack

[Audit Fix] - Added tests for EIP 712 attack

---

packages/frontend/src/components/Strategies/Crab/CrabMigrate.tsx
packages/frontend/src/components/Strategies/Crab/CrabPosition.tsx
packages/frontend/src/components/Strategies/Crab/MigrationNotice.tsx

- Updates early access narrative to make it clearer that users are committing to crab v2, not depositing yet 
- Adds steps so users understand they have to approve and commit 
- Updates information text to make it clear to users that committing to crab v2 means their deposit will be automatically transferred upon launch 
- Move helper text to tooltip
Locally

UI: update early access narrative

---

packages/hardhat/contracts/interfaces/IEuler.sol
packages/hardhat/contracts/mocks/MockEulerDToken.sol
packages/hardhat/contracts/strategy/CrabMigration.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/package.json
packages/hardhat/test/e2e/crab-Migration.ts
packages/hardhat/test/unit-tests/strategy/crab-migration.ts

- The dToken variable in CrabMigration lacks a validation check.
- Add a require statement to ensure that the dToken is weth

[Audit Fix] - [L-2] - Missing validation on dToken

---

packages/hardhat/contracts/strategy/CrabMigration.sol
packages/hardhat/test/unit-tests/strategy/crab-migration.ts

- Crab migration error codes were mixed up due to merges
- Fixing tests and contract to use correct error codes

Fix Migration Error Codes

---

packages/frontend/src/constants/enums.ts
packages/frontend/src/hooks/useTransactionHistory.ts

Add Crab V2 Deposits/Withdrawals to Tx History

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx
packages/frontend/src/hooks/useCrabPosition/useCrabPosition.ts
packages/frontend/src/pages/positions/CrabPosition.tsx
packages/frontend/src/pages/positions/Positions.tsx

Crab V2 Position

---

packages/frontend/src/abis/crabMigration.json
packages/frontend/src/components/Strategies/Crab/CrabPositionV2.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx
packages/frontend/src/pages/positions/Positions.tsx
packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/crabMigration/hooks.ts

Added position fixes to crab V2

Position fixes for crab v2

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx
packages/frontend/src/constants/index.ts
packages/frontend/src/state/crab/hooks.ts

Show deposit warning when:
Current IV < max(historicalIV * 0.9, historicalIV - 0.08)
Show withdraw warning when:
Current IV > max(historicalIV * 1.1, historicalIV + 0.08)
Show price impact warning when: 
abs(currentIV - executionIV) > max(0.1 * current IV, 0.08)

Crab V2 Funding & Price Impact Warnings

---

packages/frontend/pages/index.tsx
packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/squeethPool/hooks.ts

State is updated in a async function. Where it updates the state after calling getImmutables . This getImmutables can respond with any delay.
That's it should work normally. Where once you get all the ticks data (ticks.length = 547). It will be fully initialised pool.
But due to async nature, rarely 2nd getImmutable be responded after the 3rd getImmutable. In that call ticks will be null(stale state) and you don't have the pool.

Fix flashdeposit bug

---

packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Strategies/Crab/CapDetails.tsx
packages/frontend/src/components/Strategies/Crab/CapDetailsV2.tsx
packages/frontend/src/components/Strategies/Crab/StrategyHistory.tsx
packages/frontend/src/components/Strategies/Crab/StrategyHistoryV2.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfo.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfoV1.tsx
packages/frontend/src/components/Strategies/StrategyInfoItem.tsx

fix strategies page 
added CSS to make the website mobile friendly
bug fix 
- [ x ]Bug fix (non-breaking change which fixes an issue)
development & production environments on local & checked screen widths 🖥 
- [ x] I have performed a self-review of my own code
- [ x] I fully understand the user problem this PR is solving
- [x ] I know who the target user is for this PR and have a deep understanding of that user
- [x ] I have tried this flow thinking from the pov of the target user for this PR

regan is suddenly a front end engineer 

---

packages/frontend/src/components/Strategies/Crab/CrabPositionV2.tsx
packages/frontend/src/hooks/useCrabPosition/useCrabPosition.ts
packages/frontend/src/hooks/useTransactionHistory.ts
packages/frontend/src/lib/pnl.ts
packages/frontend/src/pages/positions/Positions.tsx

Individual PnL showing only unrealized value 

Individual pnl unrealized

---

packages/frontend/src/state/wallet/apis.ts

Disabled AML Check for local environment

Don't do AML check for dev mode

---

packages/frontend/pages/index.tsx
packages/frontend/pages/pos-merge.tsx
packages/frontend/pages/positions.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Announcement.tsx
packages/frontend/src/components/Modal/Modal.tsx
packages/frontend/src/markdown/pos-merge.md

- Show POS announcement
- Disable if "don't show again" is pressed

Add POS merge announcement

---

packages/frontend/src/state/squeethPool/hooks.ts

Use WEB3 estimate rather than uniswap's estimate
Fixes ENG-602

Fix gas issue

---

packages/frontend/pages/mint.tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx

Add a new mint page that uses LP page's mint functionality
Fixes ENG-603

Add mint page

---

packages/frontend/src/components/Strategies/Crab/StrategyPnLV2.tsx
packages/frontend/src/constants/diagram.ts

- Made axes clearer on the pnl graph
- Added a constant zero horizontal axis to make graph easier to read
Fixes # ENG-594
https://linear.app/opyn/issue/ENG-594/make-pnl-graph-axes-clearer

Make crabv2 pnl axes clearer

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx

Update slippage message to include discord link

---

packages/frontend/src/pages/positions/Positions.tsx
packages/frontend/src/state/positions/providers.tsx

Check's onchain data to evaluate the position
Fixes ENG-677

Fix wrongly showing as short position

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/FlashBull.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/src/PayableBull.sol

Setting bull variable names across contracts to match [spec](https://www.notion.so/opynopyn/Bull-Smart-Contract-Spec-885c2b19a1e040e4ae15d4d47df8fa67).

Bull Variable Names

---

packages/frontend/src/constants/index.ts

Update the warning for deposits or withdrawal slippage to warn if there is > 10 vols of slippage.
View the slippage on f/e to determine

Feat: update funding warning threshold

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/FlashBull.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/src/interface/IBullStrategy.sol
packages/bull-vault/test/e2e/FlashBullTestFork.t.sol

Refactor to only calculate squeeth, eth, and crab prices when necessary.

Bull Price Refactor

---

.github/workflows/tests.yml
packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/FlashBull.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/src/interface/IBullStrategy.sol
packages/bull-vault/test/e2e/BullStrategyTestFork.t.sol
packages/bull-vault/test/e2e/FlashBullTestFork.t.sol

**Should be merge after #683**

Feat: flash withdraw

---

packages/frontend/pages/strategies.tsx

ui: fix typo

---

packages/bull-vault/test/integration-test/BullStrategyTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol
packages/bull-vault/test/util/TestUtil.t.sol

refactor tests

---

packages/bull-vault/src/AuctionBull.sol
packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/src/interface/IBullStrategy.sol
packages/bull-vault/test/integration-test/AuctionBullTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

Before a leverage rebalance, confirms that delta and CR do not get out of our guardrail constant ranges.

Check Valid Leverage Rebalance

---

packages/frontend/src/state/ethPriceCharts/atoms.ts

ui: update default days on long pnl graph

---

packages/bull-vault/src/FlashBull.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

- Added the ability to trade between diff USDC/oSQTH pool based fee
- Refactored flashDeposit to have struct as arg

Feat: diff fee for pool in flashDeposit & refactoring

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/FlashBull.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/test/integration-test/BullStrategyTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

**Should be merged after #712**
check cap based on ETH deposited in Euler

Feat: check cap at deposit

---

packages/bull-vault/src/FlashBull.sol
packages/bull-vault/src/LeverageBull.sol

Rename ethToLend/ ethFromEuler... to WethToLend/WethFromEuler...
Fixes # Fixes ENG-832

Update ethToLend to wethToLend

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/EmergencyShutdown.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/src/interface/IBullStrategy.sol
packages/bull-vault/src/interface/ILeverageBull.sol

[WIP] refactor shutdown logic to use external contract

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/test/unit-test/BullStrategyTest.t.sol
packages/bull-vault/test/util/TestUtil.t.sol

Fix: crab balance accounting

---

packages/bull-vault/src/AuctionBull.sol

Added functions that pull and push orders to remove repeated code and refactor into a function.
Fixes ENG-864
PR Gas:
Main Gas:

Feat/refactor repeated code in AuctionBull to a function

---

packages/frontend/src/hooks/useUsdAmount.ts
packages/frontend/src/state/ethPriceCharts/atoms.ts

Get's near by price if the exact price not available

Fix NaN issue

---

packages/frontend/src/constants/diagram.ts

Remove configuration that created the space on both axes 

Fix begining gap on crab PnL chart  

---

packages/bull-vault/test/integration-test/AuctionBullTestFork.t.sol

Adds test for delta too high that works
Adds test for delta too low that is dependent on other fixes

add delta test

---

packages/frontend/src/hooks/useENS.ts

ENS is using defaultprovider which creates 429 error. Switched to using our web3 provider

Use web3 provider while getting ENS name

---

packages/frontend/src/components/Charts/CrabStrategyV2PnLChart.tsx

Ensures labels do not overlap on chart by using Highcharts default settings
Fixes ENG-925

Fix overlapping chart labels

---

packages/frontend/pages/positions.tsx

In the position page, migrated shares are not included in calculating the position. It's added now

Include migrated shares for crabv2

---

.github/pull_request_template.md

Chore: update pull request template

---

packages/frontend/src/components/Nav.tsx
packages/frontend/src/hooks/useAmplitude.ts
packages/frontend/src/utils/amplitude.ts

Added amplitude events in navbar on click

added tracking events for amplitude

---

packages/frontend/src/state/controller/utils.ts
packages/frontend/src/state/squeethPool/hooks.ts

Trade page is not working on the initial load because of dependency variables. Which is fixed now

Fix trade not working on initial load

---

packages/frontend/pages/index.tsx

ui: add tooltips for ppl to learn about what squeeth is

---

packages/frontend/pages/index.tsx

ui: update title to colon instead of dash

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/state/ethPriceCharts/atoms.ts

ui: add tooltips to projections explaining premiums taken into account

---

packages/frontend/src/state/squeethPool/hooks.ts

Use Uniswap Quoter to fetch the oSQTH price for faster loading times
Earlier we were using AlphaRouter to fetch the oSQTH price, which was taking a lot of time to load. Also it wasn't really needed since we just want the price of 1 oSQTH. 
This PR substitutes AlphaRouter with Uniswap's Quoter.
Keep an eye on the "loading price" spinner (image below). Now it takes much less time to load.

fix: use uniswap quoter to fetch osqth price for faster loading times

---

packages/frontend/src/components/Charts/FundingChart.tsx
packages/frontend/src/components/Charts/ShortFundingChart.tsx

Show daily premium upto 4 decimal places

ui: show daily premium upto 4 decimal places

---

packages/frontend/pages/strategies.tsx

Profit threshold reading v1 value. Updated to read v2 value

Fix: Update percent to read crab v2 values

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/state/trade/atoms.ts

- Debounce "Long" position inputs for better UX
- Don't override the oSQTH value when oSQTH balance  < value.
https://www.loom.com/share/2c09b2ae075a47ebbac581a05ee5d4a3

debounce inputs for better UX

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx
packages/frontend/src/state/crab/hooks.ts

Noticed that the value was amounting to NaN because of dividing by 0. This PR makes sure that doesn't happen.

fix: don't divide by 0

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2.tsx
packages/frontend/src/hooks/useStateWithReset.ts

Reset input value when token changes
https://www.loom.com/share/0c06c0688b11475da368bf1b2c3cbb99

fix: reset input values on token toggle

---

packages/bull-vault/src/LeverageZen.sol

fix natspec

---

packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Strategies/Crab/CrabPositionV2.tsx
packages/frontend/src/constants/enums.ts

style: increase tab label font size

---

packages/frontend/pages/_app.tsx
packages/frontend/src/components/Nav.tsx

Fixed repeated reporting of routing analytics to amplitude
The problem was caused due to Nav component being used on multiple pages and no centralized handler handling the routing analytics, moving it to _app.tsx solves the problem

fix amplitude routing analytics

---

packages/frontend/pages/positions.tsx
packages/frontend/src/components/Strategies/Crab/CrabPositionV2.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/styles.ts
packages/frontend/src/constants/enums.ts
packages/frontend/src/pages/positions/CrabPositionV2.tsx
packages/frontend/src/pages/positions/Positions.tsx
packages/frontend/src/state/crab/atoms.ts
packages/frontend/src/state/crab/hooks.ts

Fixes ENG-1058
Fixes ENG-1059
Fixes ENG-1061
Fixes ENG-1069
Fixes ENG-1083
Fixes ENG-1084

Netting UI fixes

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/index.tsx
packages/frontend/src/components/Trade/Confirmed.tsx

Add success confirmation for bull deposit/withdraw transactions
Demo
https://user-images.githubusercontent.com/52928941/207570150-4eb4b8ed-b01b-409a-b88a-0941506cdf97.mov

feat: Bull transaction confirmation

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/index.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/types.ts

Fix issues related to the crab transaction confirmation
FIXES ENG-1078
FIXES ENG-1066
Issues Fixed
- The wrong amount is shown in the confirmation.
- Hide Deposit/Withdraw tabs in the confirmation
- Track transaction information correctly (Standard/Instant, USDC/ETH)
Before
https://user-images.githubusercontent.com/52928941/207813648-558a6203-e766-482f-bbbc-405cac5b2bf4.mov
After 
https://user-images.githubusercontent.com/52928941/207814059-41632916-2128-46fe-8a2a-b760aeb744eb.mov

fix: crab transaction confirmation

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx

Add price impact warning in bull for deposit & withdrawal.
https://user-images.githubusercontent.com/52928941/207783833-26e541e3-ad04-492a-ba23-e8b52c337ea9.mov

feat: show price impact warnings on bull

---

packages/frontend/src/hooks/useUserCrabV2TxHistory.ts

Fix incorrect PnL on Crab Position
FIXES ENG-1085
Before
https://user-images.githubusercontent.com/52928941/207852484-e7e28a76-cb52-4edc-83eb-ff8ccdbb2e92.mov
After
https://user-images.githubusercontent.com/52928941/207852638-d1e0237b-999b-491d-b92a-ad3b45b2b0a1.mov

fix: pnl glitch crab

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx

Refresh token balance on successful deposit transaction

fix: refresh token balance on successful deposit transaction

---

packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/utils/amplitude.ts

Events tracked
DEPOSIT_STN_CRAB_USDC_CLICK
DEPOSIT_STN_CRAB_USDC_SUCCESS 
DEPOSIT_STN_CRAB_USDC_FAILED
WITHDRAW_STN_CRAB_USDC_CLICK 
WITHDRAW_STN_CRAB_USDC_SUCCESS 
WITHDRAW_STN_CRAB_USDC_FAILED

feat: track depositing/withdrawing via standard in crab

---

packages/frontend/src/components/Strategies/Bull/BullPosition.tsx

Fix PnL color on bull position
FIXES ENG-1106
Before 
After

feat: pnl colors on bull position

---

packages/zen-bull-vault/.gitignore
packages/zen-bull-vault/src/FlashZen.sol
packages/zen-bull-vault/src/LeverageZen.sol
packages/zen-bull-vault/src/UniOracle.sol
packages/zen-bull-vault/src/ZenAuction.sol
packages/zen-bull-vault/src/ZenBullStrategy.sol
packages/zen-bull-vault/src/ZenEmergencyShutdown.sol

GPL license for Zen Bull

---

packages/frontend/pages/api/auction/lastHedgeAuction.ts
packages/frontend/src/abis/eulerSimpleLens.json
packages/frontend/src/components/Strategies/Bull/BullCapDetails.tsx
packages/frontend/src/components/Strategies/Bull/BullStrategyMetrics.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/index.tsx
packages/frontend/src/constants/address.ts
packages/frontend/src/state/bull/atoms.ts
packages/frontend/src/state/bull/hooks.ts
packages/frontend/src/state/bull/utils.ts
packages/frontend/src/state/contracts/atoms.ts
packages/frontend/src/state/controller/hooks.ts
packages/frontend/src/state/positions/atoms.ts

Add bull profit threshold

---

packages/frontend/src/components/Strategies/Bull/BullStrategyInfo.tsx
packages/frontend/src/components/Strategies/Bull/BullStrategyMetrics.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Bull/index.tsx
packages/frontend/src/queries/squeeth/__generated__/strategyQuery.ts
packages/frontend/src/queries/squeeth/strategyQuery.ts
packages/frontend/src/state/bull/atoms.ts
packages/frontend/src/state/bull/hooks.ts
packages/subgraph/schema.graphql
packages/subgraph/src/bullStrategy.ts
packages/subgraph/src/constants.ts
packages/subgraph/src/crabV2.ts
packages/subgraph/src/util.ts

Use dynamic data for bull

---

packages/frontend/src/components/Strategies/Bull/BullTrade/index.tsx

fix: issues with approving withdraw bull

---

packages/frontend/src/components/Charts/BullStrategyPerformanceChart.tsx
packages/frontend/src/components/Charts/CrabStrategyV2PnLChart.tsx
packages/frontend/src/components/Strategies/Bull/index.tsx
packages/frontend/src/constants/diagram.ts
packages/frontend/src/constants/index.ts
packages/frontend/src/state/bull/atoms.ts
packages/frontend/src/state/crab/atoms.ts
packages/frontend/src/utils/pricer.ts
yarn.lock

Add bull pnl chart

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx

https://user-images.githubusercontent.com/12045121/208832299-3b8145cb-a5b0-4fe7-bc8a-bd972c0a0108.mov
https://user-images.githubusercontent.com/12045121/208832079-7c7a4a7b-2f73-4ddf-bf7d-d04480b83d67.mov

fix: fix max action for calm bull

---

packages/frontend/pages/strategies/crab.tsx
packages/frontend/src/components/Charts/BullStrategyPerformanceChart.tsx
packages/frontend/src/components/Charts/CrabStrategyV2PnLChart.tsx

- Removed comparison series for crab and zen bull charts 
- Renamed crab pnl section header from **Crab PnL** to **Performance**

Remove chart comparison series

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/constants/address.ts
packages/frontend/src/state/bull/atoms.ts
packages/frontend/src/state/bull/hooks.ts
packages/frontend/src/state/controller/hooks.ts
packages/frontend/src/state/positions/atoms.ts

Fix bull PT warning and profit threshold

---

packages/frontend/src/components/Strategies/Crab/StrategyPerformance.tsx

change tooltip title

---

packages/frontend/src/components/InputNew/InputBase.tsx
packages/frontend/src/components/InputNew/InputNumber.tsx

ref from the tooltip not passing through to the input

fix: fix ref not passing through

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/squeethPool/hooks.ts

Separate Uniswap fees & Price Impact on Deposit/Withdraw Crab

feat: separate uniswap fee and price impact on crab

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/constants/index.ts
packages/frontend/src/state/crab/atoms.ts
packages/frontend/src/state/crab/hooks.ts

Include netting amounts in price impact calculation for std deposit

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Test removing the standard deposit blue message

ui: experiment with removing standard deposit blue message

---

packages/frontend/src/state/controller/hooks.ts

https://sentry.io/organizations/opyn/issues/3534801771/?project=6653161&query=is%3Aunresolved
Fix liquidity undefined error caught by Sentry.

Liq price type error

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Quote wasn't loading when clicked on max balance for both crab and bull
FIXES ENG-1192

fix: fix max action for bull and crab

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Update high price impact warning copy on strategies

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Change tool tip copy for jumbo crab deposit and withdraw
Fixes ENG-1202

Change jumpo tool tip copy

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Fix withdraw threshold on crab.

fix: withdraw threshold on crab

---

packages/frontend/pages/strategies/crab.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/index.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/types.ts
packages/frontend/src/components/Strategies/Crab/MyPosition/index.tsx
packages/frontend/src/hooks/useCrabPosition/useCrabPosition.ts
packages/frontend/src/hooks/useUserCrabV2TxHistory.ts
packages/frontend/src/state/crab/atoms.ts
packages/frontend/src/state/crab/hooks.ts

This PR is ready as per the code fix it needed, but it still needs to be tested with new crab design.
Right now new crab does not work with Goerli 
FIXES ENG-1193
FIXES ENG-1205

fix: crab position issues after confirmed transaction

---

packages/frontend/pages/_app.tsx
packages/frontend/src/components/CrispChat/CrispChat.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/hooks/useToggleCrispChat.ts

Integrate Crisp Chat
FIXES ENG-1273
Uploading Screen Recording 2023-01-06 at 12.58.57 PM.mov…

feat: integrate crisp chat

---

packages/frontend/src/components/InputNew/InputToken.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/styles.ts
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/styles.ts

Fix font issues with bull and crab
FIXES ENG-1260
FIXES ENG-1261

fix: font issues

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/state/bull/hooks.ts

This PR adds amount, price impact and highPriceImpact data to events

fix: add more bull properties to amplitude tracking

---

packages/frontend/src/constants/address.ts

Update crab netting address to use updated crab and swaprouter for goerli.

Updated crabnetting address 

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Add vol warning for bull deposit and withdraw
Change vol warning for withdrawal by using ref vol
Fixes ENG-1143

Add funding warning for bull similar to crab

---

packages/frontend/pages/lp.tsx
packages/frontend/pages/mint.tsx
packages/frontend/pages/opt-out.tsx
packages/frontend/src/components/InputNew/InputToken.tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx
packages/frontend/src/components/Lp/LPPosition.tsx
packages/frontend/src/components/Lp/ObtainSqueeth.tsx
packages/frontend/src/components/Lp/ProvideLiquidity.tsx
packages/frontend/src/components/Lp/SelectMethod.tsx
packages/frontend/src/components/Lp/SqueethInfo.tsx
packages/frontend/src/components/Lp/Stepper.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/styles.ts
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/styles.ts
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Mint.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/components/Trade/SqueethMetrics.tsx
packages/frontend/src/components/Trade/index.tsx
packages/frontend/src/constants/index.ts
packages/frontend/styles/globals.css

LP page redesign
Affects:
- /lp page
- /mint page
more details in the loom below:
https://www.loom.com/share/2b50bab72f724c4ea217b7dea22eff82

UI: LP page redesign

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/state/bull/hooks.ts

 Exclude fee from PI calculation

---

packages/frontend/src/state/bull/hooks.ts

fix: use our own gas estimates for bull transactions

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

ui: update tooltip for standard deposits and withdraws

---

packages/frontend/pages/_app.tsx

ui: update tab name to Opyn and meta tags to include strategies

---

packages/frontend/pages/_middleware.ts

Use cloudfare headers to get country code

---

packages/services/graph-node/docker-compose.yml
packages/subgraph/src/bullStrategy.ts
packages/subgraph/src/constants.ts
packages/subgraph/src/controller.ts
packages/subgraph/src/util.ts
packages/subgraph/subgraph.template.yaml

Fix: Add eth Amount returned in bull deposited amount calculation

---

packages/frontend/pages/api/auction/lastHedgeAuction.ts
packages/frontend/src/types/index.ts
packages/frontend/src/utils/pricer.ts

Use only crab hedge's price to calculate price bands

---

.circleci/config.yml
.gitmodules
packages/zen-bull-netting/.env.example
packages/zen-bull-netting/.gitignore
packages/zen-bull-netting/README.md
packages/zen-bull-netting/foundry.toml
packages/zen-bull-netting/remappings.txt
packages/zen-bull-netting/script/Counter.s.sol
packages/zen-bull-netting/src/Counter.sol
packages/zen-bull-netting/test/Counter.t.sol

Init zen-bull-netting project

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

fix: pi warning for bull and crab withdraw

---

packages/frontend/pages/index.tsx
packages/frontend/pages/lp.tsx
packages/frontend/pages/mint.tsx
packages/frontend/pages/opt-out.tsx
packages/frontend/pages/pos-merge.tsx
packages/frontend/pages/positions.tsx
packages/frontend/pages/privacy-policy.tsx
packages/frontend/pages/strategies/bull.tsx
packages/frontend/pages/strategies/crab.tsx
packages/frontend/pages/terms-of-service-faq.tsx
packages/frontend/pages/terms-of-service.tsx
packages/frontend/pages/vault/[vid].tsx

Use Opyn in site's title and description.
Regression thing.

fix: use opyn in site title and description

---

packages/frontend/src/components/Strategies/Bull/MyPosition/index.tsx

feat: launch share pnl for bull

---

packages/frontend/src/components/Strategies/SharePnl.tsx

Fix application error on loading crab page

---

packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Charts/ShortChart.tsx
packages/frontend/src/components/Charts/VaultChart.tsx
packages/frontend/src/components/Nav.tsx
packages/frontend/src/components/SettingsMenu.tsx
packages/frontend/src/components/Strategies/Bull/About/index.tsx
packages/frontend/src/components/Strategies/Crab/About/index.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfoV1.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfoV2.tsx

all links now updated to the new gitbook hub. 

update links to new docs

---

packages/frontend/src/hooks/useUserCrabV2TxHistory.ts
packages/frontend/src/utils/apollo-client.ts

Fix crab loading issue

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Don't override users crab deposit option

---

packages/frontend/src/utils/apollo-client.ts

update satsuma url

---

packages/frontend/src/utils/apollo-client.ts

Add fathom tracking

---

packages/frontend/pages/_app.tsx

Include www. domain for fathom

---

packages/frontend/pages/_app.tsx
packages/frontend/src/components/Strategies/Bull/StrategyPerformance.tsx
packages/frontend/src/components/Strategies/Crab/StrategyPerformance.tsx

Chance tvl to open interest

---

packages/frontend/pages/_app.tsx
packages/frontend/src/components/Strategies/Bull/StrategyPerformance.tsx

Fix bull open interest

---

packages/frontend/src/components/LandingPage/DesktopLandingPage.tsx
packages/frontend/src/components/Nav.tsx

fix: landing page spacing issues

---

packages/frontend/src/components/LandingPage/DesktopLandingPage.tsx
packages/frontend/src/components/LandingPage/MobileLandingPage.tsx
yarn.lock

Update incorrect links in navigation.

update faq links

---

packages/frontend/package.json
packages/frontend/src/components/Strategies/Bull/About/ProfitabilityChart.tsx
packages/frontend/src/components/Strategies/Bull/MyPosition/index.tsx
packages/frontend/src/components/Strategies/Bull/StrategyPerformance.tsx
packages/frontend/src/components/Strategies/Crab/About/ProfitabilityChart.tsx
packages/frontend/src/components/Strategies/Crab/MyPosition/index.tsx
packages/frontend/src/components/Strategies/Crab/StrategyPerformance.tsx
packages/frontend/src/components/Strategies/styles.ts
yarn.lock

Add a shimmer loading on crab, will add to bull once approved on crab

feat: shimmers

---

packages/zen-bull-netting/foundry.toml
packages/zen-bull-netting/src/NettingLib.sol
packages/zen-bull-netting/src/ZenBullNetting.sol
packages/zen-bull-netting/src/interface/IZenBullStrategy.sol
packages/zen-bull-netting/test/fuzzing/ZenBullNetting/DepositAuctionFuzzing.t.sol
packages/zen-bull-netting/test/integration-test/ZenBullNetting/DepositAuction.t.sol

Fix wethToLend calculation

---

packages/zen-bull-vault/test/integration-test/EmergencyWithdraw/EmergencyRepayEulerDebtTest.t.sol

Extra test

---

packages/frontend/package.json
packages/frontend/pages/_app.tsx
packages/frontend/pages/api/updateBlockedAddress.ts
packages/frontend/src/components/AccountWarning.tsx
packages/frontend/src/components/RestrictionInfo.tsx
packages/frontend/src/constants/index.ts
packages/frontend/src/context/restrict-user.tsx
packages/frontend/src/server/firebase-admin.ts
packages/frontend/src/state/wallet/apis.ts
packages/frontend/src/utils/firestore.ts
yarn.lock

Block ofac addresses

---

packages/frontend/README.md
packages/frontend/middleware.ts

Debug with console log

---

packages/frontend/src/markdown/terms-of-service.md

Update ToS copy
Fixes ENG-1929

docs: update copy

---

packages/frontend/src/context/restrict-user.tsx

Allow withdrawals for everyone regardless of whether they are restricted or blocked
Fixes ENG-1928

fix: allow withdrawals for everyone

---

packages/frontend/middleware.ts

test allowed ips

---

packages/frontend/middleware.ts

Added timestamp to check if the VPN cache entry isn't too old. Currently the deadline is set to 15 days, so all the entries before 15 days won't be considered.
Fixes ENG-1970

feat: expiry based vpn cache

---

packages/frontend/middleware.ts
packages/frontend/src/constants/index.ts
packages/frontend/src/server/ipqs.ts

Exclude datacenter IPs from VPNs
Fixes ENG-1944

feat: allow datacenter ips

---

.sentryclirc

Remove Sentry authorization key (not ours)

fix: remove sentry key

---

.circleci/config.yml

remove zen-bull jobs
Remove jobs not being used in CI

chore: remove zen-bull jobs

---

packages/frontend/pages/api/tvl.ts
packages/frontend/src/hooks/useTVL.ts

fix TVL on landing page
was getting a CORS error. now fixed.
Fixes RES-120

fix: fix tvl

---

packages/frontend/src/utils/apollo-client.ts

chore: update the graph query urls

update graph query urls

---

packages/frontend/src/markdown/terms-of-service.md

update ToS domain
Fixes ENG-2520

update tos domain

---

packages/frontend/src/components/Nav.tsx
packages/frontend/src/utils/formatter.ts

Request from Legal to add new text for British users. 
Goal was to create something similar to Uniswap's implementation.
Result:
Fixes (ENG-2627)
- [ X] New feature

Feat: Banner for UK Users <ENG-2627>

---

packages/frontend/pages/_app.tsx
packages/frontend/src/components/StrikeWarning.tsx
packages/frontend/src/constants/index.ts

`/terms-of-service` and `/privacy-policy` routes are hidden behind the location blocker. 
Alterations to restricted blocker for `/terms-of-service` and `/privacy-policy`.
Fixes (ENG-2538)

FEAT: Terms of Service & Privacy Policy Change <ENG-2538>

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

change language
change crab strategy standard deposit / withdraw language on squeeth
Fixes ENG-2779

change language

---

packages/frontend/src/components/Trade/SqueethMetrics.tsx

fix eth settlement price

---

packages/frontend/pages/squeeth.tsx
packages/frontend/src/components/Alerts/ShutdownAlert.tsx

change links

---

packages/frontend/src/components/Strategies/Bull/BullTrade/ShutdownEmergencyWithdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/state/bull/hooks.ts

More fixes

---

packages/frontend/src/components/Trade/SqueethMetrics.tsx
packages/frontend/src/state/controller/hooks.ts
packages/frontend/src/state/controller/utils.ts

Shutdown fixes
