opynfinance/squeeth-monorepo

packages/frontend/src/utils/pricer.ts

Updated backtest formula with a reference to our [research paper](https://github.com/opynfinance/Research/blob/master/squeeth/whitepaper/Squeeth.pdf), adding missing item to the calculation
Locally
The updated formula in the research paper:

fix: update backtest formula for long squeeth pnl

---

packages/frontend/src/context/wallet.tsx

dont hardcode blocknative onboard to infura
Changing how the walletConnectOptions are passed to the blocknative onboard 
Now instead of all ways passing infura, it will respect the param use Alchemy
tested locally by setting usealchemy = true

fix(wallet):  dont hardcode blocknative onboard to infura

---

packages/frontend/pages/vault/[vid].tsx

Hides withdraw button for restricted users
This PR hides withdraw button for restricted users
Ensure that vault page doesn't show withdraw button for restricted user

Hides withdraw button for restricted users

---

packages/frontend/src/hooks/useETHPriceCharts.tsx

Fix .reduce bug that crashes app
This stops reduce method from running if array is empty
This PR can be tested by checking to see if the app crashes due to the reduce methods in useUsdAmount.ts

Fix .reduce bug that crashes app

---

packages/frontend/src/components/Trade/Short/index.tsx

- When a user inputs an amount of oSQTH greater than their short amount in their vault, the collateral to redeem field shows the wrong value 
Locally

fix: collateral to redeem field on short close

---

packages/frontend/pages/positions.tsx
packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Charts/VaultChart.tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx
packages/frontend/src/components/Lp/LPTable.tsx
packages/frontend/src/components/PositionCard.tsx
packages/frontend/src/components/Trade/History.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/context/lp.tsx
packages/frontend/src/context/trade.tsx
packages/frontend/src/context/world.tsx
packages/frontend/src/hooks/contracts/useController.ts
packages/frontend/src/hooks/contracts/useSqueethPool.ts
packages/frontend/src/hooks/usePositions.ts

Need to use a global context for eth price and oSQTH bal instead of trade context which doesn't reach all components 
Locally

Use world context instead of trade context for eth price and osqth bal

---

packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Strategies/StrategyInfoItem.tsx
packages/frontend/src/components/TradeSettings.tsx
packages/frontend/src/constants/enums.ts

- Adds tooltips to liquidations, spot price, and rebalance time 
- Adds timezone to rebalance time 
- Updates slippage to the same pattern as the trade page, making it more of a default
- Updates descriptions to test 
Locally

Add tooltips, timezone, update slippage and descriptions

---

packages/frontend/next.config.js

Add X-Frame-options to avoid clickjacking
It is set to sameorigin so it can be displayed in the frame if it only has the same origin. Refer here https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
You can see X-Frame-options in the response header

Add X-Frame-options

---

packages/frontend/pages/positions.tsx
packages/frontend/src/components/Strategies/Crab/CrabPosition.tsx
packages/frontend/src/constants/enums.ts

- Add loading state to PnL on crab positions 
- Update tooltip copy for min PnL 
- Add tooltip to strategies page positions card 
- Emphasize dollar values on positions page with ETH values in caption since strategy aims to be profitable in dollar terms
Locally

feat: some crab positions updates

---

packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/hooks/usePositions.ts

- Fixes position showing minted when user is long by explicitly setting mintedDebt to 0 if a user does not have a short vault 
- Fixes short/open showing 0 on confirmation modal
part of #94 (the minted part, leaving it open because doesn't fix the switching part) #33
Locally

fix: position showing minted when a user is long & short/open showing 0 on confirmation modal

---

packages/frontend/src/hooks/usePositions.ts
packages/frontend/src/lib/pnl.ts

This PR reverts the unrealized pnl calc to calculate unrealized pnl without ethCollateral pending when the ethCollateral calc is ready to be merged.

Temp updates to shortUnrealizedpnl cal

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx

- Similar to trade page show price impact as green if below 1% and red color + red button if above 3% (video is ropsten)
https://user-images.githubusercontent.com/13340486/151072230-ed12d1fd-8f69-4f49-b468-28bcc76f986f.mov
Locally

feat: price impact colors and button change

---

packages/frontend/src/components/Trade/Short/index.tsx

- Use the more conservative contract short amount value for close position on the trade page until manual mints + sells are taken into account because otherwise it is completely missing manual mints and sells for now
Locally

fix: temporarily use contract short amount for closing until manual mints + sells are take into account

---

packages/frontend/pages/index.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Charts/ShortSqueethPayoff.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Strategies/Crab/StrategyInfo.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/hooks/contracts/useController.ts
packages/frontend/src/utils/pricer.ts

- Show longest historical daily funding possible from Uniswap twap 
- Update copy re usd profitability and implications around depositing with low funding 
- Add warning if users are trying to deposit and current implied funding is less than 75% of historical daily funding 
- Update payoff diagram to 1 day return (note reverting this for this PR, can be included in another PR when we figure out how to better zoom in on the chart to display the return)
https://user-images.githubusercontent.com/13340486/151259420-2a058b31-b3cb-4f2f-a823-97085fa1522d.mov
Locally

feat: update crab explanations, warnings, payoff

---

packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/context/crabStrategy.tsx

Disable deposit / withdraw if the auction is running
- Time hedge auction is checked from the contract directly
- Price hedge auction time is stored in firebase and this will be disabled if firebase API key is not provided

Add auction warning

---

packages/frontend/src/components/Charts/LongChart.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx

- Update risks copy and add warning for high vol on long side if current vol is 75% greater than historical vol
- Update low vol error UI on crab trade 
- Update collat ratio on short / trade card
Locally

feat: update risks seciton and add high vol warning on long side

---

packages/frontend/src/context/wallet.tsx

Making coinbase wallet to default to false
Right now when i try to connect to walletlink, it takes us to coinbase wallet.
( cannot reproduce this on local host. only seen this happen on squeeth.com)
So making the preferred as false to mitigate that issue
tested locally to see that i was able to connect to both wallet link and coinbase wallet

make preferred as false

---

packages/frontend/src/lib/pnl.ts

Fixes the shortPnLCalc to be `(ETHEarnedFromSelling - ETHToPayToClosePosition) * ethPriceNow`
Locally

fix: short PnL calc

---

packages/frontend/src/components/Input/PrimaryInput.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/components/Trade/index.tsx
packages/frontend/src/constants/enums.ts
packages/frontend/src/hooks/usePositions.ts

- Disables input when on full close
- Adds tooltip to inform the user to select partial close to partially close.
#63 

On "full close" for shorts, stop users from partially closing their position

---

.gitignore
packages/frontend/package.json
packages/frontend/pages/index.tsx
packages/frontend/pages/lp.tsx
packages/frontend/pages/positions.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/components/Lp/GetSqueeth.tsx
packages/frontend/src/components/Lp/SqueethInfo.tsx
packages/frontend/src/components/Strategies/Crab/CrabTrade.tsx
packages/frontend/src/components/Trade/History.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx
packages/frontend/src/context/crabStrategy.tsx
packages/frontend/src/hooks/contracts/useController.ts
packages/frontend/src/hooks/contracts/useShortHelper.ts
packages/frontend/src/hooks/contracts/useSqueethPool.ts
packages/frontend/src/hooks/useETHPrice.ts
packages/frontend/src/hooks/usePositions.ts
packages/frontend/src/hooks/useVaultData.ts
yarn.lock

https://github.com/opynfinance/squeeth-monorepo/issues/11
Looks like calling `useController()` in many different places is causing repeat API calls to Infura/Alchemy. This PR attempts to reduce the number of API calls by reducing the number of `useController()` calls.
Ideally this alone would fix issue 11, but it alone cannot. I think there are two places where the API calls really skyrocket from `useController()` - inside `packages/frontend/src/hooks/usePositions.ts` there are two function `usePositions` and `useShortPositions`. Replacing the `const { getDebtAmount } = useController()` with a dummy method reduces a lot of API calls, which leads me to suspect that if the `getDebtAmount` method could be extracted out from `useController()`, a lot of API calls could be removed.
Fixes # …

fix: reduce number of calls made to infura/alchemy

---

packages/frontend/src/components/Nav.tsx

I found it strange that the Squeeth logo in the nav redirected to https://www.opyn.co/ instead of https://squeeth.opyn.co so I fixed.
It hasn't

fix(nav): Update link from opyn to squeeth

---

packages/frontend/pages/_app.tsx
packages/frontend/pages/positions.tsx
packages/frontend/src/context/wallet.tsx
packages/frontend/src/hooks/useETHPrice.ts
packages/frontend/src/hooks/usePositions.ts
packages/frontend/src/lib/pnl.ts

> I found that the issue was because sometimes the historic price(twelvedata) data is not being fetched cos the number of calls exceeds our limit per minute. I was getting `{"code":429,"message":"You have run out of API credits for the current minute. 663 API credits were used, with the current limit being 377. Wait for the next minute or consider switching to a higher tier plan at https://twelvedata.com/pricing","status":"error”}` error and historic price was returning zero when that happened.
> What I have done is ;
- Reduce the number of calls being made per user by ensuring that we only fetch the historic price for swaps that are relevant to the current user's position (see getRelevantSwaps lib/pnl.ts), and cache fetched historic price so that it doesn't keep calling the endpoint for …

Fix Pnl loading issues

---

README.md

Node LTS (16.14.0) should be used because latest Node (17.6.0) encounters:
```
$ yarn install
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git"] is trying to unpack in the same destination "/Users/rootulp/Library/Caches/Yarn/v6/npm-ethereumjs-abi-0.6.8-ee3994657fa7a427238e6ba92a84d0b529bbcde0/node_modules/ethereumjs-abi" as pattern ["ethereumjs-abi@^0.6.8","ethereumjs-abi@^0.6.8","ethereumjs-abi@0.6.8","ethereumjs-abi@0.6.8"]. This could result in non-deterministic behavior, skipping.
error @apollo/federation@0.27.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <17.0". Got "17.6.0"
error Found incompatible module.
```

chore: clarify that Node LTS should be used

---

packages/hardhat/contracts/interfaces/IController.sol
packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/FlashControllerHelper.sol
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

This PR add the feature of closing a short position and buying WPowerPerp with the remaining funds.
The `flashWBurnBuyLong()` will:
- flashswap WPowerPerp token
- close the short position
- Remove collateral and repay flashswap
- Long WPowerPerp token using remaining ETH

feat: flash close short and buy long

---

packages/frontend/src/components/SettingsMenu.tsx

no response after clicking the doc menu item in prod
Add key for menu item to fix it.
#251 
- Go to https://squeeth.opyn.co/
- Click on ... on top right of page
- Click "Docs" item

feat: fix settings menu issue

---

packages/frontend/src/state/squeethPool/hooks.ts

oSQTH quote is not working if ETH input changes.
- Issue is due to pool object is not changing if ticks data is changing
- So updated pool as dependency array.

Fix: Buy quote not working initial load

---

packages/frontend/pages/_app.tsx

Add embed image to head section of page to enable preview when squeeth is shared in twitter.
> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.
Fixes #218 (issue)

feat: add embed image for twitter preview

---

packages/frontend/.eslintrc
packages/frontend/src/components/PositionCard.tsx
packages/frontend/src/hooks/useAppCallback.tsx
packages/frontend/src/hooks/useAppEffect.tsx
packages/frontend/src/hooks/useAppMemo.tsx
packages/frontend/src/utils/stringifyBigNumDeps.ts

We used to have an eslint issue using a stringified version of Big number inside hooks dependency.
The big number can't be used as a dependency directly because it's an object, and lint shouldn't complain about a stringified big number. So, we tend to ignore dependency lint issues and sometimes miss necessary dependency though lint catches it, which causes critical UI bugs. 
This PR introduces useAppEffect, useAppMemo, useAppCallback, which you can pass Big number as a dependency directly without string conversion.
If you miss a necessary dependency, lint will complain about it. We shouldn't ignore any lint issues in new hooks.

Custom hooks for handling bignumber depdancy

---

packages/hardhat/contracts/periphery/ControllerHelper.sol

This remove the if statements to check if passed vaultID as param is different than 0 for functions that will not be used with vaultId == 0.
Fixes #293 

fix: remove unnecessary vaultId checks

---

packages/subgraph/schema.graphql
packages/subgraph/src/constants.ts
packages/subgraph/src/controller.ts
yarn.lock

1. add transaction.from and params.sender to vaultHistory for tx history query, cuz current useVaultHistory only supports query by vault id
2. This is the prerequisites of issue #26 
Tested with https://api.thegraph.com/subgraphs/name/yichiehliu/squeeth

feat: add from and sender to subgraph vault history

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/hooks/contracts/useTokenBalance.ts
packages/frontend/src/state/positions/hooks.ts

- Update tokenBalanceQueryKeys to include relevant variables ensuring osqth bal is always updated.
#220 
1.	Open a long position buy buying squeeth from long/open.
2.	close the page.
3.	Re-open the page and try to close oSQTH position by selling from long/close on the trade page.

Long/Close didn't load a user's oSQTH balance

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/contracts/periphery/lib/LiquidityAmounts.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

Details:
- branched from fix/excess-amounts
Fixes:
- updated to use slot0 for currentTick instead of twap
- updated to use SqrtPriceMathPartial logic instead of the existing logic in LiquidityAmounts, but left in the code commented out do decide which one to use.  Probably should investigate the differences. It might just be the ability to round up instead of round down, but not 100% sure yet.
- updated tests to check that the amount minted is close to amount LP'd with (less than 10wei difference)
- updated tests to correctly test 100% oSQTH positions
- added test where we try to mint way too much oSQTH and confirm that contract mints around the correct amount
- removed checkExcess() from mintAndLp()
Notes:
- Still seeing small excess positions of oSQTH after uniswap positions are …

Fix: (WIPish) Improvements/fixes to "fix excess amounts when LPing" PR

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/hardhat.config.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

This PR will make sure only WETH is used during the execution of any of the ControllerHelper functionalities, it only unwrap to ETH and use it when depositing collateral into vault or when sending back funds to user at the end of the transaction.
- Wrap any sent ETH to WETH as fist step in any payable function
- Wrap any removed ETH from vault to WETH
- Unwrap WETH before any collateral deposit to vault
- Unwrap all WETH balance at the end of transaction to send back ETH to user
Fixes #334 #357 #358 

wrap/unwrap ETH pattern

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts

- Determine amount to desired to mint before LPing
- Refactor MintIntoVault to DepositIntoVault

fix: determine desired amounts before LPing

---

packages/frontend/pages/vault/[vid].tsx

Fix max removable collateral amount when clicking max button in adjust collateral section of vault page
Fixes #309 

Fix max removable collateral amount in vault page

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/components/Trade/Short/index.tsx

Task:
- Fixes wrong getBuyQuote for eth params which causes error with the open long transaction.
- Replaces getSellQuoteForETH with getSellQuote which may also be causing a similar error on long close transactions.
#368 

Fix buy params sent to a trade seems not to be loaded

---

.circleci/config.yml
packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/UniswapControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperUtil.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts
packages/hardhat/test/integration-tests/periphery/controller-helper.ts

This will allow choosing different uniswap pool from fe/user.
Fixes #294 

Add Uniswap pool fee as functions arg

---

packages/frontend/pages/api/historicalprice.ts
packages/frontend/pages/api/twelvedata.ts
packages/frontend/src/hooks/useETHPrice.ts
packages/frontend/src/lib/pnl.ts

Fix unrealised PnL loading very slowly
- ETH historical price is currently fetched sequentially
- It now uses complex_data API which fetches data parallelly for us and gives in single result (It will still cost API credits. ie: If we request the price for 5 timestamps, it will still count as 5 APIs)
Fixes #422 
- [] New feature (non-breaking change which adds functionality)

Add historical price to async request 

---

packages/frontend/pages/vault/[vid].tsx
packages/frontend/src/hooks/useVault.ts

Instead of using vault id from the query param. UI uses the user's first vault. This behavior is changed in this PR
test https://squeeth.opyn.co/vault/70 and https://continuouscall-git-fix-vault-data-missing-opynfinance.vercel.app/vault/70 to see the difference

Fix vault data not showing for non user vaults

---

packages/frontend/src/components/Trade/Long/BreakEven.tsx
packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/utils/calculations.ts

Add breakeven ETH price in long squeeth
Here's the calculation for breakeven https://docs.google.com/spreadsheets/d/1k1Y_WZ4Of9Prsn5hpHX2BXfdPuUg24X_KBrgYvV8Yw4/edit#gid=0

Add breakeven to long squeeth

---

packages/frontend/styles/globals.css

https://github.com/opynfinance/squeeth-monorepo/issues/445
While running Next.js on local, overflow hidden is automatically applied to the body. It makes it hard to work on the strategies and positions page.
Unset the overflow style of the body to show scroll always
Fixes # (issue) https://github.com/opynfinance/squeeth-monorepo/issues/445

Fix scroll not working in development

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/UniswapControllerHelper.sol

Fix: using different uniswap pool in flashswapWBurnBuyLong() and flashswapSellLongWMint()

---

packages/hardhat/contracts/periphery/ControllerHelper.sol
packages/hardhat/contracts/periphery/lib/ControllerHelperDataType.sol
packages/hardhat/test/e2e/periphery/controller-helper.ts

This PR remove adding the amount to flashloan to the collateral to deposit when minting and LP, there this will allow the user to user any extra amount flashloaned as amount to LP,  and will repaid later when withdrawing from vault.
In the function call, the amount to flashloan and to use as vault collateral should be added in the collateral to deposit param.
Fixes #399 

Include flashloan amount in collateralToDeposit to allow user to use vault collateral to LP

---

packages/frontend/src/state/positions/atoms.ts
packages/frontend/src/state/positions/hooks.ts

Position sometimes reloads randomly
This loading issue isn't related to API calls. It happens when calculating position fees which involve a lot of big numbers calculation. So it only occurs when the computer is slow. This PR removes the fees calculation loading to avoid flickering. I confirmed it's fixed by throttling CPU 6x.
Fixes # (issue) https://github.com/opynfinance/squeeth-monorepo/issues/365

Fix position flickering issue

---

packages/frontend/pages/index.tsx
packages/frontend/src/components/PositionCard.tsx

Issue: When the advanced details dropdown is open and the arrow is hovered over prior to closing it, the shaded area overlaps with the Norm Factor tooltip. 
This change makes it like an accordion, such that user can open and close with the same button.

fix advanced details close button overlapping Norm Factor tooltip

---

packages/hardhat/contracts/strategy/CrabStrategyV2.sol

When remaining amount is greater than or equal to zero, we run the loop one extra time for the last order with zero quantity as remaining. This is not necessary

Bug Fix: Remaining amount shoud be greater than the quantity

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/state/squeethPool/hooks.ts

Before: we used a fixed const for long position slippage
Now: using the user-inputted slippage amount

Slippage bug fix

---

packages/hardhat/contracts/strategy/CrabMigration.sol
packages/hardhat/test/e2e/crab-Migration.ts
packages/hardhat/test/unit-tests/strategy/crab-migration.ts

- add withdrawV1Shares function
- update unit tests
- update e2e tests

[Audit Fix] [L-7] - User crabV1 tokens can get stuck when the owner does not launch migrate

---

packages/hardhat/contracts/strategy/CrabMigration.sol
packages/hardhat/test/e2e/crab-Migration.ts

we are sending all the token in the contract to the msg.sender [here](https://github.com/opynfinance/squeeth-monorepo/blob/main/packages/hardhat/contracts/strategy/CrabMigration.sol#L277). So it also sends the token that are not claimed yet!

Fix: Transfer all crabs to a flash migrating user

---

packages/frontend/src/components/Trade/Long/index.tsx
packages/frontend/src/state/squeethPool/hooks.ts

Before: using fixed slippage amount and overriding when sending minimum amount out
Now: using user inputted slippage amount from get-go

Slippage quote fix

---

packages/frontend/src/hooks/contracts/useTokenBalance.ts

Before, long and short positions only conditionally showed up since oSQTH balance showed up as 0.
https://user-images.githubusercontent.com/29926727/180891654-89bb6c88-b286-410c-9810-e19110c93ded.mov
This was due to an issue where polling was wrongfully set to false, even when variables only differed since one was null.

Token Balance Bug Fix

---

packages/frontend/src/queries/uniswap/__generated__/subscriptionSwaps.ts
packages/frontend/src/queries/uniswap/__generated__/subscriptionSwapsRopsten.ts
packages/frontend/src/queries/uniswap/__generated__/swaps.ts
packages/frontend/src/queries/uniswap/__generated__/swapsRopsten.ts
packages/frontend/src/queries/uniswap/swapsQuery.ts
packages/frontend/src/queries/uniswap/swapsRopstenQuery.ts
packages/frontend/src/state/positions/hooks.ts

Before: Depositing into crab showed up as a short position in the amount of the swap. This was because the GraphQL query which uses Uniswap's subgraph omitted swaps with the oSQTH-ETH pool that were called from the Crab V1 contract, but not the Crab V2 contract.
Now: The GraphQL query which uses Uniswap's subgraph omits swaps with the oSQTH-ETH pool that are called from **either** the Crab V1 **or** Crab V2 contract.
- Open a crab position & make sure it does not show a short position
- Partial close crab position & make sure it does not show a short or long position
- Fully close crab position & make sure it does not show a 0 oSQTH long position
- Open/close a long position & make sure it just shows the proper long position
- Open/close a short position & make sure it just shows the …

Crab V2 Short Position Bug Fix

---

packages/frontend/src/state/crab/hooks.ts
packages/frontend/src/state/squeethPool/hooks.ts

- Sometimes `calculateETHtoBorrowFromUniswap` returns 0, because tick list length is 0 https://github.com/Uniswap/v3-sdk/blob/6e59ae3e893ae738767446c1e1d19a5c6a2c9588/src/utils/tickList.ts#L41
- In this fix I only initialize pool after getting the tick list data
- To make sure if this issue never happens, I am also showing an alert / throwing the error if ethToBorrow is 0

WIP: Flashdeposit frontrun

---

packages/frontend/src/components/Charts/FundingChart.tsx
packages/frontend/src/hooks/useNormHistory.ts
packages/frontend/src/queries/squeeth/__generated__/normalizationFactorUpdates.ts
packages/frontend/src/queries/squeeth/normHistoryQuery.ts
packages/frontend/src/state/wallet/hooks.ts

Funding/vol stopped on Aug. It's because we were using skip in subgraph query, which has limited usage of 5000. So any data more than 5000 we should last ID as suggested [here](https://thegraph.com/docs/en/querying/graphql-api/#pagination)
Fixes ENG-790

Fix vol chart

---

packages/bull-vault/src/BullStrategy.sol
packages/bull-vault/test/integration-test/BullStrategyTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

- call redeemCrabAndWithdrawWEth() with non-auction address, revert - Fixes ENG-868
- call depositEthIntoCrab() with non-auction address, revert  - Fixes ENG-869
- remove setCap 0 size restriction  - Fixes ENG-870
- tests successful cap set (assert correct value set)
Fixes ENG-867
PR coverage:
Main coverage:

Feat/ Improve BullStrategy coverage

---

packages/bull-vault/src/LeverageBull.sol
packages/bull-vault/test/integration-test/BullStrategyTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

- setAuction revert if address(0) - Fixes ENG-850
- setAuction revert if not owner - Fixes ENG-851
- setAuction successfully set auction address  - Fixes ENG-852
- auctionRepayAndWithdrawFromLeverage() revert with non auction caller - Fixes ENG-853
- depositAndBorrowFromLeverage() revert with non auction caller - Fixes ENG-854
- remove the if statement in _depositWethInEuler for _wrapEth - Fixes ENG-855
- delete _isAuction() in LeverageBull - Fixes ENG-856
- fixes incorrect error code for address(0) input in setAuction()
Fixes ENG-849
PR Coverage:
Main Coverage:

Feat / Improve LeverageBull tests / coverage

---

packages/bull-vault/src/FlashBull.sol
packages/bull-vault/test/integration-test/BullStrategyTestFork.t.sol
packages/bull-vault/test/integration-test/FlashBullTestFork.t.sol

- implement local _getCrabVaultDetails() instead of calling BullStrategy
- refactor _calcWsqueethToMintAndFee() to only call twap when needed
- local variable of powerTokenController instead of calling BullStrategy for it
Fixes ENG-892
Gas PR:
Gas Main:

Feat/ FlashDeposit gas optimization

---

packages/frontend/pages/index.tsx
packages/frontend/src/components/Charts/LongChart.tsx

Just a couple of style improvements targeted towards smaller screen sizes.
All the following images are of iPhone 12 Pro (width: 390px)

style improvements for small screens

---

packages/frontend/pages/index.tsx
packages/frontend/pages/strategies.tsx
packages/frontend/src/components/Charts/LongChart.tsx

Previously couldn't see squeeth info (iv, ref vol etc.) or change the historical days for long squeeth PnL on mobile. This allows users to do that on mobile. 
Tested locally

ui: add squeeth info (vol, ref vol etc.) and historical days adjustment to long squeeth mobile 

---

packages/frontend/src/components/Trade/Short/index.tsx

Layout shifts while changing the short squeeth close from dropdown, This PR Fixes that.
Before:
https://user-images.githubusercontent.com/52928941/205659331-cce2d83b-549d-487a-86ef-b5f4d8882001.mov
After: 
https://user-images.githubusercontent.com/52928941/205659555-d3fefefd-be9c-4570-abbc-99e37622d2ef.mov
Change comparison in dev tools:
https://user-images.githubusercontent.com/52928941/205706256-c580247a-99dc-4e69-8da3-a54b8b2f3135.mov

[Fix] Layout issue caused by short squeeth close dropdown

---

packages/frontend/src/components/Button/WalletButton.tsx

Nav items getting overlapped.
Solution: Doesn't make sense to show that many characters for the wallet address IMO. To keep it uniform with the squeeth address, let's show only the starting 6 and the ending 4 chars.

fix: nav items getting overlapped

---

packages/frontend/src/components/Nav.tsx

Further fixes the nav items overlapping issue by reducing the width of contract address button.

style: further fixes the nav items overlap issue

---

packages/frontend/src/components/Strategies/Crab/StrategyHistoryV2.tsx
packages/frontend/src/hooks/useCrabV2AuctionHistory.ts
packages/frontend/src/state/crab/atoms.ts

Add a load more button on strategy hedges.
This would show 10 initial entries with a load more button (if there are more entries), once you click on load more it loads the next 10 and navigates to the end of the page smoothly.
UX Comparison
Before 
https://user-images.githubusercontent.com/52928941/205851337-e7ae9436-a6ba-4383-8eea-9f4f482ee12e.mov
After 
https://user-images.githubusercontent.com/52928941/205851367-e18546a6-cad6-4663-b088-d4241df16cd9.mov

[Feature] Add load more button to strategy hedges for smooth user experience

---

packages/frontend/src/components/Strategies/Crab/StrategyHistoryV2.tsx
packages/frontend/src/state/crab/atoms.ts

Show 3 records initially and fetch 3 incrementally in strategy hedges (crab)
https://user-images.githubusercontent.com/52928941/206382104-f8f63711-d22a-4b68-8270-64b7655cdff2.mov

fix: show 3 strategy hedges initially and show 3 incrementally

---

packages/frontend/src/components/Metric.tsx

As discussed with @iamoperand, reducing the padding for small metric component due to width increasing issue of trade card caused by slippage and price impact value metrics

fix: small metric padding

---

packages/frontend/src/constants/enums.ts

Remove `flash` from transaction history on bull
FIXES ENG-1112

fix: remove `flash` from transaction history on bull

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx

Update wrong analytics event name in bull withdraw

fix: update wrong analytics event name in bull withdraw

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx

Fix price impact warning for bull & crab when oSQTH value is trading lower than its minimum value. 
FIXES ENG-1124
FIXES ENG-1108
Note: we need to add more aggressive warning for this issue, right now fixing it with price impact warning.

fix: price impact warnings on crab & bull.

---

packages/frontend/src/hooks/useCrabPosition/useCrabPosition.ts
packages/frontend/src/hooks/useETHPrice.ts
packages/frontend/src/hooks/useUserBullTxHistory.ts
packages/frontend/src/hooks/useUserCrabV2TxHistory.ts

The issue was happening whenever we switched from one wallet to another, with both wallet having crab transactions. 
Reason: Immediately after switching the wallet `timestampsArr` got updated but `ethUsdPriceMap` didn't (still getting fetched), as a result the corresponding `ethUsdValue` was coming out to be null.
https://user-images.githubusercontent.com/12045121/209807783-7644b238-b787-4a64-b33f-29b36c61dd58.mov
https://user-images.githubusercontent.com/12045121/209807787-e58d3637-f4cc-4d18-b2de-e3ae3157b5ac.mov
Fixes ENG-1194

fix: pnl not showing sometimes

---

packages/frontend/pages/strategies/crab.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/index.tsx

Not a bug as such, just wanted to move it to where it belongs.
`setStrategy` is used to set the strategy data (TVL, ETH price at last hedge, max cap) so it should run as soon as the crab page loads, not when the crab trade section loads.

fix: move setStrategy from crab trade to crab page, where it belongs

---

packages/frontend/src/components/Trade/Long/index.tsx

Add Loader to Deposit button on long squeeth instead of inside input
FIXES ENG-1184

fix: quote loading on long squeeth

---

packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/state/bull/hooks.ts

Split Uniswap fees on bull deposit/withdraw
FIXES ENG-1180
Before
After

feat: split uniswap fees from price impact on bull

---

packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

Hide crab yield deposit warning & costly withdrawal warning on standard deposit crab
FIXES ENG-1201

fix: crab deposit/withdraw warnings

---

packages/frontend/src/components/Nav.tsx

Highlight Strategies link in the navigation bar for both bull and crab
FIXES ENG-1289

fix: highlight strategies link for both bull and crab strategy pages

---

packages/frontend/src/components/Strategies/Bull/StrategyPerformance.tsx
packages/frontend/src/components/Strategies/Crab/StrategyPerformance.tsx

Fix show loading on strategy performance (both crab/bull) instead of 0 numbers for returns.
FIXES ENG-1259

fix: show loading on strategy performance instead of 0 value

---

packages/frontend/src/components/CrispChat/CrispChat.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Deposit.tsx
packages/frontend/src/components/Strategies/Bull/BullTrade/Withdraw.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx

fix: show crisp chat to everyone and show the offline message to users if they respond offline.

fix: show crisp chat to everyone 

---

packages/frontend/src/state/bull/hooks.ts

Add gas to amplitude tracking of bull transactions

fix: track gas estimate in bull transactions

---

packages/frontend/src/utils/amplitude.ts
packages/frontend/src/utils/apollo-client.ts

Add response load time to amplitude for subgraph queries

Add apollo client metrics

---

packages/frontend/pages/strategies/index.tsx

**/strategies** was showing nothing when opened directly via the link. only client side was working.
Fixes ENG-1447

fix: add server side redirect for /strategies

---

packages/frontend/src/components/Metric.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Deposit.tsx
packages/frontend/src/components/Strategies/Crab/CrabTradeV2/Withdraw.tsx
packages/frontend/src/components/Trade/Mint.tsx

fix MetricLabel's fontsize
As a result of incorrect size, the selected metric label's don't look aligned. "Price Impact" is slightly bigger than "Uniswap Fee".

fix: fix MetricLabel's fontsize

---

packages/frontend/middleware.ts

fix: get the correct client ip from cloudflare reverse proxy

---

packages/frontend/middleware.ts

Reduce cache expiry time from 30 days to 3 days
Originally, the setting was for 30 days, indicating that when a data center is whitelisted, existing users would only gain access to the site after 30 days from their initial visit. However, a 3-day period seems to be an optimal balance, reducing the frequency of API calls while also avoiding issues with outdated data.
Fixes ENG-2043

reduce cache expiry time to 3 days
